apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
data:
  database: wordpress
  user: wordpress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
data:
  host: wordpress-mysql
  user: wordpress
